export const GET_ERRORS = "GET_ERRORS";
export const UPDATE_RESULT = "UPDATE_RESULT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const  UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES";
export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_STUDENT_GROUPES = "GET_STUDENT_GROUPES";

export const UPDATE_USER_STATE = "UPDATE_USER_STATE";

export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";




